Add dummy test; Simplify msg test;

diff --git a/trunk/tests/Makefile b/trunk/tests/Makefile
--- a/trunk/tests/Makefile
+++ b/trunk/tests/Makefile
@@ -13,14 +13,15 @@ MODULES = \
 			prefs \
 			slide \
 			video \
+			dummy \
 
 all:
 	@for i in $(MODULES); do \
-		$(ECHO) -n "Module $$i " && (cd $$i && make -s) && $(ECHO) "$(OK)" && continue || $(ECHO) "$(FAILED)" && exit; \
+		$(ECHO) "Test $$i " && (cd $$i && make -s) && continue || exit; \
 	done
 
 clean:
 	@for i in $(MODULES); do \
-		$(ECHO) -n "Module $$i " && (cd $$i && make -s clean) && $(ECHO) "cleaned $(OK)" && continue || $(ECHO) "$(FAILED)" && exit; \
+		$(ECHO) -n "Test $$i " && (cd $$i && make -s clean) && $(ECHO) "cleaned $(OK)" && continue || $(ECHO) "$(FAILED)" && exit; \
 	done
 
